---
- hosts: 172.31.9.235
  become: yes
  tasks:
  - include_tasks: myfile.yml
  -   name: i want to install apache2 server (apt-get install apache2)
      apt:
        name: apache2
        state: present 

  -   name: i want to start apache2 webserver (service apache2 start)
      service:
        name: apache2
        state: started
       
