---
- hosts: 172.31.13.124
  become: yes
  tasks:
  - include_tasks: myfile.yml
  -   name: I want to create folder
      file:
        path: /home/saif/myfolder
        state: directory
        notify: webserver
        
  handlers:
  -   name: webserver
      copy:
        src: mytextfile
        dest: /home/saif/myfolder/mytextfile

  -   name: download any internt file
      get_url:
        url: https://updates.jenkins.io/download/war/2.508/jenkins.war
        dest: /home/saif/myfolder/jenkins.war
        force_basic_auth: yes

  -   name: I want to copy index fileto host node
      template:
        src: myindex.j2
        dest: /var/www/html/index.html

  