---
- hosts: 172.31.13.124
  become: yes
  tasks:
  - include_tasks: myfile.yml
  -   name: I want to create folder
      file:
        path: /home/saif/myfolder
        state: directory
  -   name: I want to copy file to folder
      copy:
        src: mytextfile
        dest: /home/saif/myfolder/mytextfile

  