---
- hosts: all
  become: yes
  tasks:
  - name: i want to install apache2 server (apt-get install apache2)
    apt:
      name: apache2
      state: present   
    when: ansible_os_family=="redhat"

  - name: i want to start apache2 webserver (service apache2 start)
    service:
      name: apache2
      state: started
    when: ansible_os_family=="redhat"
